# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATASOURCE - POSTGRESQL LOCAL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/telco
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SQL INIT (schema.sql + data.sql)
# ===============================
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

# ===============================
# JWT CONFIG (JJWT 0.12.3)
# ===============================
app.jwt.secret=6dJ93kLx8vP2qWzR5tNyB7uMfGhK4cQa1XyZpE8r
app.jwt.expiration-minutes=240

# ===============================
# LOGGING
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=INFO